'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Capa_Cliente.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1486486278_arrow_minimize_reduce_shrink_81220() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1486486278-arrow-minimize-reduce-shrink_81220", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1486486297_attribute_category_label_shop_price_price_tag_tag_81213() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1486486297-attribute-category-label-shop-price-price-tag-tag_81213", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1486504830_delete_dustbin_empty_recycle_recycling_remove_trash_81361() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1486504830-delete-dustbin-empty-recycle-recycling-remove-trash_81361", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1486505253_folder_folder_up_folder_upload_update_folder_upload_81427() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1486505253-folder-folder-up-folder-upload-update-folder-upload_81427", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1491254088_8document_arrow_up_82913() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1491254088-8document-arrow-up_82913", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1492692368_7email_83536() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1492692368-7email_83536", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1492692368_7email_835361() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1492692368-7email_835361", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3643769_building_home_house_main_menu_start_113416() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3643769-building-home-house-main-menu-start_113416", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3844443_disable_eye_inactive_see_show_view_watch_110296() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3844443-disable-eye-inactive-see-show-view-watch_110296", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property actions_edit_clear_15784() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("actions_edit_clear_15784", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property administrative_tools_15497() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("administrative_tools_15497", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property aov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property backup_and_restore_15493() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backup_and_restore_15493", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bootloader_users_person_people_6080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bootloader_users_person_people_6080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property box_full_products_14639() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("box_full_products_14639", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property center_text_icon_icons_com_71505() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("center-text_icon-icons.com_71505", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property community_users_12977() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("community_users_12977", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property community_users_129771() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("community_users_129771", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property contactlist_theuser_802() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("contactlist_theuser_802", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property diagram_43_24474() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diagram-43_24474", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property document_delete_256_icon_icons_com_75995() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_delete_256_icon-icons.com_75995", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property documentediting_editdocuments_text_documentedi_2820() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("documentediting_editdocuments_text_documentedi_2820", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Exit_Page_icon_icons_com_53732() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exit-Page_icon-icons.com_53732", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property file_listing_2_icon_icons_com_58366() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("file-listing-2_icon-icons.com_58366", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_saved_search_16890() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_saved_search_16890", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_saved_search_168901() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_saved_search_168901", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_symbol_of_letter_a_icon_icons_com_73556() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font-symbol-of-letter-a_icon-icons.com_73556", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_cancel_97589() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic-cancel_97589", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property information_info_1565() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("information_info_1565", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property korganizer_task_tasks_list_9500() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("korganizer_task_tasks_list_9500", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Line_ui_icons_Svg_10_icon_icons_com_72171() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Line_ui_icons_Svg-10_icon-icons.com_72171", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_stencil_others() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo-stencil-others", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property new_page_document_16676() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_page_document_16676", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property new_page_document_166761() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_page_document_166761", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property newfile_85903() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newfile_85903", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Print_icon_icons_com_73705() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Print_icon-icons.com_73705", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Print_icon_icons1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Print_icon-icons1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RGB_Circle_1_80_icon_icons_com_57282() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RGB_Circle_1-80_icon-icons.com_57282", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property search_find_window_16723() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_find_window_16723", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property search_find_window_167231() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_find_window_167231", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sega_Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sega-Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tab_client_icon_icons_com_72436() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tab_client_icon-icons.com_72436", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property text_align_left_icon_icons_com_71322() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text-align-left_icon-icons.com_71322", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property text_align_right_icon_icons_com_71321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text-align-right_icon-icons.com_71321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property trans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property unnamed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unnamed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property window_minimize_icon_138009() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("window_minimize_icon_138009", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property world_logo_template_png_83839() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("world-logo-template-png_83839", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property xmag_search_find_export_locate_5984() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xmag_search_find_export_locate_5984", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
